-- Scriba — schema has moved to a versioned migration.
-- Run this instead (Supabase SQL editor, or `supabase db push`):
--   supabase/migrations/0001_initial_schema.sql
-- This file is kept only as a redirect pointer.
